// Generated by CoffeeScript 1.10.0
(function() {
  var FeedbackController;

  FeedbackController = (function() {
    function FeedbackController(io) {
      console.log("io: ", io);
      this.io = io;
      console.log("Feedback control ready");
    }

    FeedbackController.prototype.audioNotification = function(clip) {
      console.log("Play audio: " + clip);
      this.io.emit('new message', {
        message: "Howling333!",
        username: "Legion"
      });
      return this.io.emit('play audio', {
        file: clip
      });
    };

    FeedbackController.prototype.visualNotification = function(domID, msg) {};

    FeedbackController.prototype.time = function(elapsed) {};

    FeedbackController.prototype.handVisible = function(visible) {};

    FeedbackController.prototype.confidenceMeter = function(confidence) {
      var adjustedConfidence;
      return adjustedConfidence = confidence * 100;
    };

    return FeedbackController;

  })();

  module.exports = FeedbackController;

}).call(this);
