// Generated by CoffeeScript 1.10.0
(function() {
  var FeedbackController;

  FeedbackController = (function() {
    function FeedbackController(config) {
      this.config = config;
      console.log("Feedback control ready");
    }

    FeedbackController.prototype.audioNotification = function(clip) {
      return console.log("TODO: Play audio: " + clip);
    };

    FeedbackController.prototype.visualNotification = function(domID, msg) {
      return console.log("TODO: Visual notification: " + domID + ", " + msg);
    };

    FeedbackController.prototype.time = function(elapsed) {
      return console.log("TODO: Feedback time: " + elapsed);
    };

    FeedbackController.prototype.handVisible = function(visible) {
      return console.log("TODO: Hand visible: " + visible);
    };

    FeedbackController.prototype.confidenceMeter = function(confidence) {
      var adjustedConfidence;
      adjustedConfidence = confidence * 100;
      return console.log("TODO: Show confidence: " + adjustedConfidence);
    };

    return FeedbackController;

  })();

  module.exports = FeedbackController;

}).call(this);
